name: pet_list
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
    flutter:
      sdk: flutter
    firebase_core: ^2.4.0  # Adicione esta linha para Firebase Core
    cloud_firestore: ^4.4.0  # Adicione esta linha para Firestore
    cupertino_icons: ^1.0.8
    uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
